### PR TITLE
implement wires

### LINKED ISSUE #3: Wires
Enable selecting two objects and connect a wire between them.
 
 How the actual implementation works is left for investigation by @steenish. 
 
 ### Suggestions
 - Select first object -> "Add wire" -> (Wire created attached to first object) -> Select other object -> "Attach wire" -> Objects connected
 - Select first object -> Select other object simultaneously -> "Connect objects" -> Objects connected

### PR DESCRIPTION
**Pull request by steenish**
This should address all the things to do with wires, i.e. renderer, physics and circuit interface.

closes #3

### CODE REVIEW

**Review by raaavioli — APPROVED** [review]
It's a little tough trying to understand every piece of the circuit code, but I couldn't see any obvious things to point out. If we ever add support for splitting cables and joints, then we would probably have to update code for checking the circuit. Also, I could not see if we ever look for a negative pool of a battery at the end of a trace. Do we do that?

The wire code seems nice aswell.

**Comment by steenish** [comment]
@raaavioli the circuit code is a work in progress on the circuits branch and will not be fully functional right now, though it is needed for making the wire interface.

I don't know what you mean by a negative pool, could you elaborate?

**Comment by raaavioli** [comment]
@steenish 
> I don't know what you mean by a negative pool, could you elaborate?

My terminology is probably poor, but I mean a current will always go from a positive "pool" of a battery to a negative "pool" elsewhere, possibly on the same battery. Do we take into account that for a circuit to be complete, the current needs to end in a negative pool of some battery along its path? I would assume so, but I was just wondering, because I could not find it in the code.

**Comment by steenish** [comment]
@raaavioli the way it works right now, limited to connections in series, the circuit won't be considered closed unless it connects back to the negative pole of the battery which started the circuit trace

**Pull request closed without merging**
