### PR TITLE
Battery fix and knife switch

### PR DESCRIPTION
**Pull request by codecat22**
Battery finally correct for demo.

The knife switch has no animation yet but otherwise should be fine?

### CODE REVIEW

**Review by raaavioli — DISMISSED** [review]
Lgtm, didn't check in Unity, but changes seem fine.

**Comment by raaavioli** [comment]
After merging the wire-code we seem to have some conflict. Can you have a look at resolving it @codecat22?

**Comment by codecat22** [comment]
> After merging the wire-code we seem to have some conflict. Can you have a look at resolving it @codecat22?

on it

**Review by raaavioli — APPROVED** [review]
Good job 🥳

**Pull request merged**
